USE [master]
GO
ALTER DATABASE [CLINICA] ADD FILEGROUP [FG_DATOS]
GO
ALTER DATABASE [CLINICA] ADD FILE ( NAME = N'DATOS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DATOS.ndf' , SIZE = 8192KB , FILEGROWTH = 65536KB ) TO FILEGROUP [FG_DATOS]
GO


CREATE TABLE CLINICA..TABLA1(
	DATO VARCHAR(100)
) ON FG_DATOS;
GO


